- name: Déployer l'image Docker sur l'instance EC2
  hosts: web
  become: true

  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
      tags: docker

    - name: Lancer le conteneur Docker
      docker_container:
        name: myapp
        image: myapp:latest
        state: started
        restart_policy: always
      tags: docker
