---
- name: Déployer l'image Docker sur l'instance EC2
  hosts: web
  become: true

  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      tags: docker

    - name: Lancer le conteneur Docker
      docker_container:
        name: myapp
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"

      tags: docker
